#!/usr/bin/env bash

export ydb_gbldir=/opt/yottadb/yottadb.gld
export ydb_dir=/opt/yottadb
export ydb_routines="/opt/qoper8/m /usr/local/lib/yottadb/r138/libyottadbutil.so"
export ydb_dist=/usr/local/lib/yottadb/r138

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

npm install nodem



