#!/usr/bin/env bash

export ydb_gbldir=/opt/yottadb/yottadb.gld
export ydb_dir=/opt/yottadb
export ydb_routines="/opt/mgateway/m /usr/local/lib/yottadb/r138/libyottadbutil.so"
export ydb_dist=/usr/local/lib/yottadb/r138

$ydb_dist/mumps -run $1


